include: package:very_good_analysis/analysis_options.5.1.0.yaml

analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.gr.dart'
    - 'lib/feature/onboarding/view/mixin/onboarding_builder_mixin.dart'
    - 'pubspec.yaml'
