name: moonx
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.7.0
  flutter_svg: ^2.0.10+1


  # State Management
  flutter_bloc: ^8.1.5
  bloc: ^8.1.4

  # Cache
  hydrated_bloc: ^9.1.5

  # Core
  equatable: ^2.0.5
  path_provider: ^2.1.2
  intl: ^0.19.0
  kartal: ^4.0.3

  # Google
  json_annotation: ^4.8.1

  # Routing
  auto_route: ^8.0.3
  auto_route_generator: ^8.0.0

  # Dependency Injection
  get_it: ^7.6.8

  # Utils
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  table_calendar: ^3.1.1

  # Network
  dio: ^5.4.2+1

  gen:
    path: package/gen

dev_dependencies:
  flutter_test:
    sdk: flutter



  # Lints
  very_good_analysis: ^5.1.0

  # Code Generation
  json_serializable: ^6.7.1
  build_runner: ^2.4.9

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
