name: moonx
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.7.0
  flutter_svg: ^2.0.10+1


  # State Management
  flutter_bloc: ^8.1.5
  bloc: ^8.1.4

  # Cache
  hydrated_bloc: ^9.1.5

  # Core
  equatable: ^2.0.5
  path_provider: ^2.1.2
  intl: ^0.19.0
  kartal: ^4.0.3

  # Google
  json_annotation: ^4.8.1
  google_generative_ai: ^0.3.0

  # Routing
  auto_route: ^8.0.3
  auto_route_generator: ^8.0.0

  # Dependency Injection
  get_it: ^7.6.8

  # Utils
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  table_calendar: ^3.1.1
  glass: ^2.0.0+1
  carousel_slider: ^4.2.1
  webview_flutter: ^4.7.0


  # Network
  dio: ^5.4.2+1

  # Audio
  audioplayers: ^6.0.0

  gen:
    path: package/gen

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Lints
  very_good_analysis: ^5.1.0

  # Code Generation
  json_serializable: ^6.7.1
  build_runner: ^2.4.9

flutter:
  uses-material-design: true

  assets:
    - assets/
