name: gen
description: "A new Flutter package project."
version: 0.0.1

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  flutter_svg: ^2.0.10+1

  # Google
  json_annotation: ^4.8.1

  # Core
  equatable: ^2.0.5
  envied: ^0.5.4+1
  envied_generator: ^0.5.4+1

  # Audio
  audioplayers: ^6.0.0

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  # Code generation
  flutter_gen_runner: ^5.4.0
  build_runner: ^2.4.9
  json_serializable: ^6.7.1

  # Linter
  very_good_analysis: ^5.1.0



flutter_gen:
  output: lib/src/asset/
  integrations:
    lottie: true
    flutter_svg: true

  colors:
    inputs:
      - assets/color/colors.xml

flutter:
  assets:
    - assets/color/
    - assets/icons/
    - assets/images/

